package tips

import "time"

// tips is a curated list of DevOps, Kubernetes, AWS, and EKS tips.
var tips = []string{
	"kubectl get events --sort-by='.lastTimestamp' shows cluster events in chronological order.",
	"Use 'kubectl top pods --sort-by=memory' to quickly find memory-hungry pods.",
	"AWS SSM Session Manager logs can be sent to S3 or CloudWatch for auditing.",
	"'kubectl rollout undo deployment/NAME' instantly rolls back to the previous revision.",
	"EKS managed node groups handle AMI updates — you just need to trigger the upgrade.",
	"'kubectl debug node/NODE -it --image=busybox' gives you a shell on any node.",
	"Use 'kubectl diff -f manifest.yaml' to preview changes before applying.",
	"AWS EKS Pod Identity simplifies IAM for pods — no more IRSA annotation juggling.",
	"'kubectl get pods -A --field-selector=status.phase!=Running' finds non-running pods fast.",
	"SSM port forwarding works without opening any inbound security group rules.",
	"'kubectl explain pod.spec.containers' is a built-in API reference — works offline.",
	"Use 'kubectl get pods -o jsonpath=\"{.items[*].spec.containers[*].image}\"' to list all images.",
	"EKS access entries let you manage cluster auth without editing aws-auth ConfigMap.",
	"'kubectl auth can-i --list' shows what your current user is allowed to do.",
	"AWS PrivateLink keeps EKS API traffic off the public internet entirely.",
	"'kubectl logs --previous' shows logs from the last crashed container instance.",
	"Use 'kubectl get pods --show-labels' to see labels without describing each pod.",
	"EKS add-ons (CoreDNS, kube-proxy, VPC CNI) can be managed declaratively via Terraform.",
	"'kubectl run tmp --rm -it --image=curlimages/curl -- sh' gives you a quick debug pod.",
	"AWS Systems Manager Parameter Store is free for standard parameters — great for config.",
	"'kubectl config get-contexts' shows all your configured clusters at a glance.",
	"Use 'kubectl top node' to see CPU and memory usage across all nodes.",
	"EKS Fargate profiles let you run pods serverless — no nodes to manage.",
	"'kubectl get pods -w' watches for changes in real time — great for rollout monitoring.",
	"AWS VPC CNI assigns real VPC IPs to pods — no overlay network overhead.",
	"'kubectl port-forward svc/NAME 8080:80' works for services, not just pods.",
	"Use 'kubectl create job --from=cronjob/NAME test-run' to trigger a CronJob manually.",
	"EKS cluster endpoint can be public, private, or both — private is most secure.",
	"'kubectl get nodes -o wide' shows node IPs, OS images, and kernel versions.",
	"AWS CloudWatch Container Insights gives per-pod metrics without installing Prometheus.",
	"'kubectl label nodes NODE-NAME disktype=ssd' lets you schedule pods to specific nodes.",
	"Use 'kubectl get pdb' to check PodDisruptionBudgets before draining a node.",
	"EKS supports Bottlerocket OS — minimal, immutable, and purpose-built for containers.",
	"'kubectl api-resources' lists every resource type your cluster supports.",
	"AWS Karpenter scales nodes faster than Cluster Autoscaler by provisioning directly.",
	"'kubectl exec -it POD -- env' quickly shows all environment variables in a pod.",
	"Use 'kubectl get endpoints' to verify service-to-pod routing is correct.",
	"EKS security groups for pods let you apply VPC-level network policy per pod.",
	"'kubectl patch' is great for quick one-off changes without editing full manifests.",
	"AWS Secrets Manager integrates with EKS via the CSI Secrets Store driver.",
	"'kubectl drain NODE --ignore-daemonsets' safely evicts pods before node maintenance.",
	"Use 'kubectl get componentstatuses' to check control plane health (or 'kubectl get cs').",
	"EKS auto mode manages compute, storage, and networking — less YAML, same Kubernetes.",
	"'kubectl cp' copies files to/from pods, but rsync in a debug container is more reliable.",
	"AWS Cost Explorer can break down EKS costs with proper resource tagging.",
	"'kubectl describe pod POD | grep -A5 Events' is the fastest way to find scheduling issues.",
	"Use 'kubectl set image deployment/NAME container=image:tag' for quick image updates.",
	"EKS Blueprints (Terraform/CDK) give you a production-ready cluster in minutes.",
	"'kubectl get po -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase' for clean output.",
	"Always tag your EKS node groups — it makes cost allocation and debugging much easier.",
	"'kubectl wait --for=condition=ready pod -l app=NAME' blocks until pods are healthy.",
	"AWS GuardDuty has EKS protection built in — it monitors control plane audit logs.",
	"'kubectl rollout status deployment/NAME' blocks until a rollout completes or fails.",
	"Use resource requests and limits — a pod without them can starve the whole node.",
	"EKS supports IPv6 clusters for massive pod density without IP exhaustion.",
	"'kubectl neat' (krew plugin) strips managed fields from YAML output — much cleaner.",
	"AWS Load Balancer Controller maps Ingress and Service resources to ALB/NLB natively.",
	"'kubectl get events --field-selector reason=FailedScheduling' surfaces scheduling problems.",
	"Use NetworkPolicies to implement zero-trust between namespaces — default-deny is safest.",
	"EKS nodes should use launch templates — instance metadata v2 (IMDSv2) is more secure.",
	"'kubectl auth whoami' (v1.28+) shows your authenticated identity in the cluster.",
	"AWS Distro for OpenTelemetry (ADOT) runs as a DaemonSet for metrics and traces.",
	"'kubectl scale deployment/NAME --replicas=0' is the quickest way to stop a workload.",
	"Always set terminationGracePeriodSeconds appropriately — 30s default may not be enough.",
}

// ForToday returns the tip of the day, rotating daily through the list.
func ForToday() string {
	day := time.Now().YearDay()
	return tips[day%len(tips)]
}
